### ISSUE TITLE
Reject queries directly selecting AID columns.

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/pg_diffix#397]
Such queries will take a long time to finish and have no chance of returning any useful results.

**Comment by pdobacz** [comment]
Is the gist of the issue here selecting or rather GROUP BY-ing? In other words, we do want to reject `SELECT count(*) GROUP BY aid;` as well, correct?

Also: we probably should not reject generalized AID columns, but I'm not 100% sure. If so, then do we look into whether the generalization is trivial or not (e.g. `substring(aid, 1, 10000)`)? I don't think that's necessary.

In general, I'm presuming we just want to cut out the obviously non-sense queries, rather than try to cover all possible edge cases.

**Comment by cristianberneanu** [comment]
> Is the gist of the issue here selecting or rather GROUP BY-ing?

Anonymized select implies grouping.

> Also: we probably should not reject generalized AID columns

Yes, let's allow generalizations of AID columns for now.

**Comment by edongashi** [comment]
@pdobacz yes, because

```sql
SELECT 1
FROM table
GROUP BY aid
```

Is equally slow and fully suppressed.

**Comment by pdobacz** [comment]
#407
